sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PPB2jHY8eRkldN8OGwkb8mlRysRlKCm5BXH7BpJPkcVP1jOTA1vpM7xNVZ5lUnygPQw0sxFjFUY80272OteG9UTgCZue1HQiDIe/9Ma8DepoOKwikNE01TyfqfUD7h/3/jq+xYmTT+Of1W3bZMtrUDBdpWZJ7KDDV8DRittZd/miaVctHfHYzdQNR4OGDmww19Y5hr+5P9FUGQrLqWYku0+k21YNOaOWni5ywcli0brLqwJnAyDJspky59W2kCskfj4axGlncrJtaONWkUt4twUGNZ2yAcU/EjEF2EquPe/bFYn5dufq85eLsZnEVtdEOJPvGlG3lewcO9fLWiKNCw2/2IkbGkwPwzI3RyomVYTOqbcwv+2Fng5d06HVet1IRM7bfDv/DF71hJ7+hru1hSEqK0cgAKnISHFHfLJBcZDDZvrhPM//43oAhu4U9/jpvVX7FjWhDI+owWu2iqY7g5a7m/B0pMqAHmZcIvx9RfM/BcHeWo1zGlxIMnTB3vom7R0QL7dotIwOIr+inmBSEgrTpDu8cfoi/W50/tTp89mJUs30hTWYyRJ0zz20IzBZaHbWmWbf3MJA2DZSD+rf99IgIsFy01HwQKMu+8HGU5VKBDIFLx0MBGOlKK6BlcX1VwvBFLd+VCfdZL79xbQxri29QVFI/6Ux77L7cBI6Fm8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/As-a-Matter-of-Course_4385
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy